import example_simple
import example_simple_log
import example_weight
import example_date_year
import example_date_ymd
import example_date_xy_ymd
import example_perc
import example_perc2
import example_fixedwidth
import example_dotplot
import example_textplot
import example_textplot
import example_multiplot_1
import example_multiplot_2

import multisplit_example
import example_multimap_1


